import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import App from "./App";
import dynamic from "next/dynamic";

const App = dynamic(() => import("./App"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store sample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="en">
      <body className={inter.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
